# Generated by Django 4.1.13 on 2024-03-28 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('html', models.TextField(blank=True)),
            ],
        ),
    ]
