# Generated by Django 5.0.2 on 2024-02-20 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_app_image_alter_app_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='app_images'),
        ),
    ]
