# Generated by Django 5.0.2 on 2024-02-27 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_app_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
